// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package math

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestSum struct {
	Num1                 int32    `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int32    `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSum) Reset()         { *m = RequestSum{} }
func (m *RequestSum) String() string { return proto.CompactTextString(m) }
func (*RequestSum) ProtoMessage()    {}
func (*RequestSum) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{0}
}

func (m *RequestSum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSum.Unmarshal(m, b)
}
func (m *RequestSum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSum.Marshal(b, m, deterministic)
}
func (m *RequestSum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSum.Merge(m, src)
}
func (m *RequestSum) XXX_Size() int {
	return xxx_messageInfo_RequestSum.Size(m)
}
func (m *RequestSum) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSum.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSum proto.InternalMessageInfo

func (m *RequestSum) GetNum1() int32 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *RequestSum) GetNum2() int32 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type ResponseSum struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSum) Reset()         { *m = ResponseSum{} }
func (m *ResponseSum) String() string { return proto.CompactTextString(m) }
func (*ResponseSum) ProtoMessage()    {}
func (*ResponseSum) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{1}
}

func (m *ResponseSum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSum.Unmarshal(m, b)
}
func (m *ResponseSum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSum.Marshal(b, m, deterministic)
}
func (m *ResponseSum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSum.Merge(m, src)
}
func (m *ResponseSum) XXX_Size() int {
	return xxx_messageInfo_ResponseSum.Size(m)
}
func (m *ResponseSum) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSum.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSum proto.InternalMessageInfo

func (m *ResponseSum) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestSum)(nil), "math.RequestSum")
	proto.RegisterType((*ResponseSum)(nil), "math.ResponseSum")
}

func init() { proto.RegisterFile("math.proto", fileDescriptor_f139a3799a86a974) }

var fileDescriptor_f139a3799a86a974 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2c, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x4c, 0xb8, 0xb8, 0x82, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x82, 0x4b, 0x73, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x4a, 0x73, 0x0d,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0xa8, 0x98, 0x91, 0x04, 0x13, 0x5c, 0xcc,
	0x48, 0x49, 0x95, 0x8b, 0x3b, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0xa4, 0x4d, 0x8c,
	0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0xaa, 0x11, 0xca, 0x33, 0x32, 0xe1, 0x62, 0xf1,
	0x4d, 0x2c, 0xc9, 0x10, 0xd2, 0xe1, 0x62, 0x06, 0x29, 0x13, 0xd0, 0x03, 0x5b, 0x8f, 0xb0, 0x4f,
	0x4a, 0x10, 0x26, 0x02, 0x37, 0x4b, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x3e, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x59, 0xaa, 0x8d, 0xb8, 0xad, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathClient is the client API for Math service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathClient interface {
	Sum(ctx context.Context, in *RequestSum, opts ...grpc.CallOption) (*ResponseSum, error)
}

type mathClient struct {
	cc *grpc.ClientConn
}

func NewMathClient(cc *grpc.ClientConn) MathClient {
	return &mathClient{cc}
}

func (c *mathClient) Sum(ctx context.Context, in *RequestSum, opts ...grpc.CallOption) (*ResponseSum, error) {
	out := new(ResponseSum)
	err := c.cc.Invoke(ctx, "/math.Math/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServer is the server API for Math service.
type MathServer interface {
	Sum(context.Context, *RequestSum) (*ResponseSum, error)
}

// UnimplementedMathServer can be embedded to have forward compatible implementations.
type UnimplementedMathServer struct {
}

func (*UnimplementedMathServer) Sum(ctx context.Context, req *RequestSum) (*ResponseSum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterMathServer(s *grpc.Server, srv MathServer) {
	s.RegisterService(&_Math_serviceDesc, srv)
}

func _Math_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/math.Math/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).Sum(ctx, req.(*RequestSum))
	}
	return interceptor(ctx, in, info, handler)
}

var _Math_serviceDesc = grpc.ServiceDesc{
	ServiceName: "math.Math",
	HandlerType: (*MathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Math_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}
